void PlaceBomb(int, int, int);
void DisplayDirection1(int, int, int);
void DisplayDirection2(int, int, int);
void ScreenMove1(void);
void ScreenMove2(void);
void TurnBombRed(int, int);
void TurnBombBlack(int, int);
void PrintExplosion(int, int);
void PrintEmpty(int, int);
void PrintPowerUp(int, int);
void PrintIntro(void);
void PrintStartImage(void);
void PrintDarkness(int, int);
void PrintWinner1(void);
void PrintWinner2(void);
void PrintDaBomb(int, int);
void PrintDaBombItem(int, int);
void PrintADC(int);
void PrintPower(int, int);
